easy_admin:
    site_name: 'Stage'
    entities:
        Users:
            class: App\Entity\Users
            list:
                fields: ['id', 'email', 'roles']
        Events:
            class: App\Entity\Event
            list:
                fields: ['id', 'title', 'image']
    design:
        brand_color: 'black'
        menu:
          - Users
          - Events
        assets:
            css:
                - '/bundles/lp/css/lp.css'
