version: '2'
services:
    birth_php:
        build: php-fpm
        ports:
            - '9004:9000'
        volumes:
            - ${PWD}:/var/www/symfony
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        links:
            - birth_db
        networks:
            main:
                aliases:
                    - birth_php

    birth_nginx:
        build: nginx
        ports:
            - '8083:80'
            - '1340:1340'
        volumes_from:
            - birth_php
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx/:/var/log/nginx:cached
        networks:
            main:
                aliases:
                    - birth_nginx
    birth_db:
        image: mariadb:latest
        restart: on-failure
        ports:
          - "3312:3306"
        volumes:
          - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
          - ./db:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=birth
          - MYSQL_USER=root
        networks:
            main:
                aliases:
                    - mysql
networks:
    main:
